

-- What this file does:
-- Demonstrates Oracle 23ai Select AI capabilities for natural language database queries.
-- Shows different AI query modes (narrate, showsql, explainsql, chat) and how they work with the SH schema.

-- Documentation to reference:
-- - Oracle 23ai Select AI: https://docs.oracle.com/en/cloud/paas/autonomous-database/select-ai/
-- - Select AI Examples: https://docs.oracle.com/en-us/iaas/autonomous-database-serverless/doc/select-ai-examples.html
-- - DBMS_CLOUD_AI Package: https://docs.oracle.com/en/database/oracle/oracle-database/23/arpls/DBMS_CLOUD_AI.html

-- Relevant slack channels:
-- - #adb-select-ai-users: questions about Oracle 23ai Select AI
-- - #igiu-innovation-lab: general discussions on your project
-- - #igiu-ai-learning: help with sandbox environment or help with running this code

-- Prerequisites:
-- 1. Oracle 23ai Autonomous Database with Select AI enabled
-- 2. Access to the SH (Sales History) sample schema
-- 3. OCI credentials configured for GenAI access

-- How to run the file:
-- 1. Update the credential details below with your OCI information
-- 2. Execute this script in SQL*Plus or SQL Developer connected to your 23ai database
-- 3. Test the various AI query examples

-- Step 1: Verify database connection
SELECT USER FROM DUAL;

-- Step 2: Create OCI credential for GenAI access
-- IMPORTANT: Replace the placeholder values below with your actual OCI credentials
-- You can find these details in your ~/.oci/config file and private key file
-- NOTE: This is your PRIVATE key, not the public key referenced in the config
BEGIN
    DBMS_CLOUD.CREATE_CREDENTIAL(
        credential_name => 'OCI_GENAI_CRED',
        user_ocid => 'your-user-ocid-here',
        tenancy_ocid => 'your-tenancy-ocid-here',
        private_key => '-----BEGIN PRIVATE KEY-----
your-private-key-content-here
-----END PRIVATE KEY-----',
        fingerprint => 'your-key-fingerprint-here'
    );
END;
/

-- Step 3: Clean up existing profile
BEGIN
    dbms_cloud_ai.drop_profile(
        profile_name => 'genaish',
        force => true
    );
END;
/

-- Step 4: Create AI profile for SH schema
BEGIN
    DBMS_CLOUD_AI.CREATE_PROFILE(
        profile_name => 'genaish',
        attributes => '{
            "provider": "oci",
            "credential_name": "OCI_GENAI_CRED",
            "model": "meta.llama-4-scout-17b-16e-instruct",
            "comments": "true",
            "object_list": [{"owner": "SH"}]
        }'
    );
END;
/

-- Step 5: Set the active profile
BEGIN
    dbms_cloud_ai.set_profile(
        profile_name => 'genaish'
    );
END;
/

-- Step 6: Configure output formatting
SET WRAP ON

-- Step 7: Sample Select AI queries demonstrating different modes

-- Basic AI query - returns natural language answer
SELECT AI 'how many customers exist';

-- Show the SQL that would be executed
SELECT AI showsql 'how many customers exist';

-- Explain the SQL that would be executed
SELECT AI explainsql 'how many customers exist';

-- Run the SQL and return results
SELECT AI runsql 'how many customers exist';

-- Narrative answer (same as basic AI query)
SELECT AI narrate 'how many customers exist';

-- Chat mode for conversational queries
SELECT AI chat 'how many customers exist';
SELECT AI chat 'why is the sky blue';

-- Complex queries with filtering
SELECT AI showsql 'how many customers in San Francisco are married';

-- Business intelligence style queries
SELECT AI 'find top 3 baby boomer big spenders';
SELECT AI showsql 'find top 3 baby boomer big spenders';

-- Example of the actual SQL generated by Select AI for the baby boomer query
SELECT * FROM (
    SELECT "CUST_FIRST_NAME", "CUST_LAST_NAME", "CUST_INCOME_LEVEL",
           "CUST_YEAR_OF_BIRTH", SUM("AMOUNT_SOLD") AS "TOTAL_SPENT"
    FROM "SH"."CUSTOMERS" "C"
    INNER JOIN "SH"."SALES" "S" ON "C"."CUST_ID" = "S"."CUST_ID"
    WHERE "CUST_YEAR_OF_BIRTH" BETWEEN 1946 AND 1964
    GROUP BY "CUST_FIRST_NAME", "CUST_LAST_NAME", "CUST_INCOME_LEVEL", "CUST_YEAR_OF_BIRTH"
    ORDER BY SUM("AMOUNT_SOLD") DESC
) WHERE ROWNUM <= 3;
